name: Assets

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.8"

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install Sass
        run: npm install --global sass@1.104.0

      - name: Compile stylesheets
        run: uv run --locked scripts/compile_sass.py
