name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no github@theodorblom.com << 'EOF'
          cd /usr/share/nginx/theodorblom.com
          git pull origin main
          uv sync --frozen --extra deploy
          uv run scripts/compile_sass.py
          sudo systemctl restart gunicorn-theodorblom
          EOF
