name: Sass output retry experiment

on:
  push:
    branches: [test/sass-output-retries]

permissions:
  contents: read

jobs:
  assets:
    uses: ./.github/workflows/test-sass-output-producer.yml

  deploy:
    needs: assets
    uses: ./.github/workflows/test-sass-output-consumer.yml
    with:
      sass_version: ${{ needs.assets.outputs.sass_version }}
